TESTS = $(wildcard *.c)
ASMS = $(TESTS:.c=.s)
CPP = hcpp.exe
CPP_FLAG = $(EXTRA_CPP_FLAG) \
-D__declspec\(a\)= -D__cdecl= -D__inline__=inline -D__extension__= \
-D__attribute__\(a\)= -D__builtin_va_list='char*' \
-D__builtin_stdarg_start=__builtin_va_start -D__asm__\(a\)= -W 0 -H

CC1 = hcc1.exe
CC1_FLAG =
TOUCH = touch
DOGV = wdog.exe -v

all:ok.log

ok.log:$(ASMS)
	$(TOUCH) $@

%.i : %.c
	$(DOGV) $(CPP) -o $@ $< $(CPP_FLAG)

%.s : %.i
	$(DOGV) $(CC1) -o $@ $< $(CC1_FLAG)
	$(TOUCH) $@

clean:
	$(RM) *.i *.s *.asm *.exe *.log a.c *~
	$(RM) -r .vs x64 Debug Release

getch.s:getch.i
getop.s:getop.i
main.s:main.i
stack.s:stack.i
